package com.smartlock.domain.enums;

public enum NotificationType {
    RESERVATION_CREATED,
    RESERVATION_CANCELLED,
    RESERVATION_CHECKED_OUT,
    ACCESS_CODE_CREATED,
    ACCESS_CODE_REVOKED,
    ACCESS_CODE_FAILED,
    SYNC_FAILED,
    SYNC_COMPLETED,
    MEMBER_INVITED,
    CLEANER_ASSIGNED,
    LOCK_DISCONNECTED,
    SUBSCRIPTION_EXPIRING
}
