package com.smartlock.domain.enums;

public enum WebhookEventType {
    RESERVATION_CREATED,
    RESERVATION_UPDATED,
    RESERVATION_CANCELLED,
    RESERVATION_CHECKED_IN,
    RESERVATION_CHECKED_OUT,
    ACCESS_CODE_CREATED,
    ACCESS_CODE_REVOKED,
    CLEANER_TASK_CREATED,
    CLEANER_TASK_COMPLETED,
    LOCK_CONNECTED,
    LOCK_DISCONNECTED
}
